package lxmf

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// stampVector is testdata/stamp_upstream.json, generated by running
// upstream LXMF's own LXStamper at the versions pinned in the spec repo's
// tools/requirements.txt (rns 1.4.2 / lxmf 1.1.1).
type stampVector struct {
	Source               string `json:"_source"`
	MaterialHex          string `json:"material_hex"`
	WorkblockRounds      int    `json:"workblock_rounds"`
	WorkblockLen         int    `json:"workblock_len"`
	WorkblockSHA256Hex   string `json:"workblock_sha256_hex"`
	WorkblockPNRounds    int    `json:"workblock_pn_rounds"`
	WorkblockPNSHA256Hex string `json:"workblock_pn_sha256_hex"`
	StampCost            int    `json:"stamp_cost"`
	StampHex             string `json:"stamp_hex"`
	StampValue           int    `json:"stamp_value"`
}

func loadStampVector(t *testing.T) (stampVector, []byte) {
	t.Helper()
	raw, err := os.ReadFile("testdata/stamp_upstream.json")
	if err != nil {
		t.Fatalf("read stamp vector: %v", err)
	}
	var v stampVector
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("decode stamp vector: %v", err)
	}
	material, err := hex.DecodeString(v.MaterialHex)
	if err != nil {
		t.Fatalf("decode material: %v", err)
	}
	return v, material
}

// TestStampWorkblockMatchesUpstream is the byte-equality check a
// self-round-trip cannot give us (playbook.md §5): our workblock and
// upstream LXStamper's must be the same 768 KiB for the same material.
//
// This is the single highest-leverage assertion in the stamp code. The
// workblock is where every implementation detail lands — HKDF salt
// construction, the msgpack encoding of the round counter, round count,
// per-round length — and a divergence in any of them is SILENT: we still
// grind a stamp, it still clears the bit target against OUR workblock,
// and every real node rejects it because theirs differs. Comparing the
// digest catches all of that at once.
func TestStampWorkblockMatchesUpstream(t *testing.T) {
	v, material := loadStampVector(t)
	t.Logf("vector source: %s", v.Source)

	if v.WorkblockRounds != workblockExpandRounds {
		t.Fatalf("vector pins %d delivery rounds, we use %d", v.WorkblockRounds, workblockExpandRounds)
	}
	if v.WorkblockPNRounds != workblockExpandRoundsPN {
		t.Fatalf("vector pins %d PN rounds, we use %d", v.WorkblockPNRounds, workblockExpandRoundsPN)
	}

	for _, c := range []struct {
		name    string
		rounds  int
		wantSHA string
		wantLen int
	}{
		{"delivery/3000", workblockExpandRounds, v.WorkblockSHA256Hex, v.WorkblockLen},
		{"propagation/1000", workblockExpandRoundsPN, v.WorkblockPNSHA256Hex, 0},
	} {
		wb, err := stampWorkblock(material, c.rounds)
		if err != nil {
			t.Fatalf("%s: stampWorkblock: %v", c.name, err)
		}
		if c.wantLen != 0 && len(wb) != c.wantLen {
			t.Errorf("%s: workblock is %d bytes, upstream produced %d", c.name, len(wb), c.wantLen)
		}
		got := sha256.Sum256(wb)
		if hex.EncodeToString(got[:]) != c.wantSHA {
			t.Errorf("%s: workblock SHA-256 = %x, upstream = %s\n"+
				"every stamp ground against this workblock would be rejected by real nodes",
				c.name, got, c.wantSHA)
		}
	}
}

// TestUpstreamStampValidates closes the loop in the other direction: a
// stamp generated by upstream LXStamper must clear our stampValid at the
// cost upstream recorded, and stampValid must agree with upstream's
// stamp_value on the exact bit count.
func TestUpstreamStampValidates(t *testing.T) {
	v, material := loadStampVector(t)
	stamp, err := hex.DecodeString(v.StampHex)
	if err != nil {
		t.Fatalf("decode stamp: %v", err)
	}
	wb, err := stampWorkblock(material, workblockExpandRounds)
	if err != nil {
		t.Fatalf("stampWorkblock: %v", err)
	}
	if !stampValid(stamp, v.StampCost, wb) {
		t.Errorf("upstream stamp rejected at its own cost %d", v.StampCost)
	}
	// stamp_value is the achieved leading-zero count, which upstream
	// exposes to applications for prioritization (§5.7.2 step 3). Ours
	// must not be off by one against it.
	digest := sha256.Sum256(append(append([]byte{}, wb...), stamp...))
	if got := leadingZeroBits(digest[:]); got != v.StampValue {
		t.Errorf("stamp_value = %d, upstream = %d", got, v.StampValue)
	}
	if stampValid(stamp, v.StampValue+1, wb) {
		t.Errorf("stamp accepted at cost %d, one bit above its actual value", v.StampValue+1)
	}
}
